animir/node-rate-limiter-flexible

- lib/RateLimiterMongo.js
When trying to use the blockDuration feature with Mongo, I stumbled into this error:
```
MongoError: the update operation document must contain atomic operators.
at Function.create (/home/drye/dev/customer/node_modules/loopback-connector-mongodb/node_modules/mongodb-core/lib/error.js:43:12)
at toError (/home/drye/dev/customer/node_modules/loopback-connector-mongodb/node_modules/mongodb/lib/utils.js:149:22)
at checkForAtomicOperators (/home/drye/dev/customer/node_modules/loopback-connector-mongodb/node_modules/mongodb/lib/operations/collection_ops.js:161:12)
at Collection.findOneAndUpdate (/home/drye/dev/customer/node_modules/loopback-connector-mongodb/node_modules/mongodb/lib/collection.js:1597:15)
at Promise (/home/drye/dev/customer/node_modules/rate-limiter-flexible/lib/RateLimiterMongo. …
```
> Fixed a Mongo bug when using forceExpire

- lib/index.d.ts
When consume returns it contains a single promise with an array of results. The previous type signature said it returned an array of promises.
> Fix RateLimiterUnion's consume TS response type

- lib/index.d.ts
This PR adds type signatures for the `toJSON` and `toString` methods of `RateLimiterRes`. I have deliberately kept the same order for `toJSON` as specified in `_getDecoratedProperties` and I have not made any properties of `toJSON` readonly, because I don't think it would be appropriate to make a JSON response non-immutable (although perhaps you could argue this).
> Add type signatures for toString and toJSON methods of RateLimiterRes

- lib/RateLimiterMongo.js
- test/RateLimiterMongo.test.js
When mongoose is used with command buffering collection should be asked from client because db might not be available before connection is established.
resolves #26
> Use collection from mongoose client

- index.js
- lib/index.d.ts
This allows using
```
if (rlRejected instanceof RateLimiterRes) {
res.set('Retry-After', String(Math.round(rlRejected.msBeforeNext / 1000)) || 1);
res.status(429).send('Too Many Requests');
} else {
throw rlRejected;
}
```
instead of 
```
if (rlRejected instanceof Error) {
throw rlRejected;
} else {
res.set('Retry-After', String(Math.round(rlRejected.msBeforeNext / 1000)) || 1);
res.status(429).send('Too Many Requests');
}
```
As just comparing instanceof Error is not accurate (see all possible classes https://nodejs.org/api/errors.html)
it's better to check if the rlRejected is instanceof RateLimiterRes and if it's not then throw the error.
> Add IRateLimiterResOptions interface and RateLimiterRes class

- lib/index.d.ts
Typing is currently incorrect for `rateLimiterInstance.get()`: it currently returns `Promise<RateLimiterRes> | null`, which breaks `Promise.all` typing (which always expects a Promise – even if it doesn't necessarily require one.. a different story).
In any case, the reality is that `.get()` should _always_ return a `Promise` anyway, so moving the possibility of `null` inside the promise result fixes both issues.
> Fix typing for rateLimiterInstance.get()

- lib/index.d.ts
The constructor signature in `RateLimiterRes.js` looks like this
```javascript
constructor(remainingPoints, msBeforeNext, consumedPoints, isFirstInDuration)
```
while the typing in `index.d.ts` looks like this
```typescript
constructor(opts: IRateLimiterResOptions);
```
I have updated the typescript type file to be inline with the javascript implementation
> Update constructor type for RateLimiterRes

- lib/index.d.ts
https://github.com/animir/node-rate-limiter-flexible/commit/2a954d3a12bc4ad2d410166f914903bd250f5fb2#diff-0e3ac3694919aca1db302bc3ebe669f2 introduced type definition for the `RateLimiterQueue` class, but its definition was partial. Therefore, Typescript compiler was issuing errors (and did not get type hints) while using this class.
> fix(Types definitions): add RateLimiterQueue missing methods

- lib/RateLimiterPostgres.js
Since node-postgres@8.0.0, the pool factory returns a `BoundPool` class instead of the `Pool` class. This resulted in the store type exception being thrown when not explicitly setting a value for `clientType`.
See:
https://github.com/brianc/node-postgres/blame/ea6ac2ad2313af57159b10a0292c0c178e8e0923/packages/pg/lib/index.js#L16
> Set correct clientType for node-postgres@8.0.0 BoundPool class

- lib/component/MemoryStorage/MemoryStorage.js
- package.json
- test/component/MemoryStorage/MemoryStorage.test.js
I wanted to try getting a memory rate limiter working in the browser. Unfortunately, `MemoryStorage` tries to call `unref()` on the result of `setTimeout`, which is a node-ism. By guarding this call, the code works in a browser. What do you think?
> unref() should be guarded so it can work on client

- README.md
- lib/RateLimiterPostgres.js
- test/RateLimiterPostgres.test.js
Implements #96 
Adds support for postgres with typeorm
Have this working in a project but was doing this little work outside and passing the pg pool instance instead.
````js
const connection = await createConnection({...});
const options = {
storeClient: connection,
storeType: 'typeorm',
...
}
const rateLimiter = new RateLimiterPostgres(opts)
````
I think same implementation should work for MySQL also. Can't test it now. Can add it later. 
Hope it works 🤞
> Add typeorm support for postgres

- LICENSE.md
The title is not legally mandated, but it's convenient for human consumption, and provides additional metadata; for that reason, it is typically included in the template text of this license, as recommended by [OSI](https://opensource.org/licenses/isc-license), [SPDX](https://spdx.org/licenses/ISC.html#licenseText), [choosealicense.com](https://choosealicense.com/licenses/isc/), and others.
***Note**: This PR is part of my personal project to improve the consistency and visibility of the ISC license in open source projects. See https://github.com/github/choosealicense.com/issues/377 for more details.*
> Add title to the LICENSE.md file

- lib/index.d.ts
Fixes #109
Also added some inline documentation, in order to have supported editors render useful information inline where the methods are used:
I ran `prettier` for formatting consistencies sake. There doesn't seem to be an editorconfig or linting setup, so my setup defaulted to tabs w/ 80-column width. Lemme know if you prefer that otherwise.
> Add missing get/set types, improve documentation

- lib/RateLimiterMongo.js
- package.json
- test/RateLimiterMongo.test.js
The `returnOriginal` option for `findOneAndUpdate` is deprecated, see https://github.com/mongodb/node-mongodb-native/blob/f916843ad2002a4c829c5f126e58e8efba257525/lib/collection.js#L1720
This should get rid of warnings like `[MONGODB DRIVER] DeprecationWarning: collection.findOneAndUpdate option [returnOriginal] is deprecated and will be removed in a later version.`
> Replace deprecated MongoDB option

- lib/RateLimiterStoreAbstract.js
- lib/component/BlockedKeys/BlockedKeys.js
- test/RateLimiterStoreAbstract.test.js
It is required when we need to manually allow specific blocked clients to pass the limiter.
> Allow cleanup in memory data

- lib/component/MemoryStorage/MemoryStorage.js
When using the delete function, I noticed that the timeouts are not cleared. This causes the timeout to be executed even if the item was already deleted. If there is already a new item with the same key in the meantime, that one will be removed.
> Remove timeout on deletion of node

- package.json
Since bundlers don't tend to add shims for node core modules any more, it's necessary to tell them what to do when the code imports a given node core module.
The change allows use of things like `RateLimiterMemory` in isomorphic js code.
> Add "browser" field to allow bundling

- lib/RateLimiterRes.js
As the node js documentation says, you need to use a global symbol to can be accessed in any environment for "util.inspect.custom":
https://nodejs.org/api/util.html#utilinspectcustom
> In addition to being accessible through util.inspect.custom, this symbol is [registered globally](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol/for) and can be accessed in any environment as Symbol.for('nodejs.util.inspect.custom').
Otherwise when building js-libp2p app for browser using Vite, you can catch the following error:
> replace "util.inspect.custom" by global Symbol for more flexible

- lib/RateLimiterRedis.js
- test/RateLimiterRedis.test.js
Pass get() and consume() calls directly to insuranceLimiter if redis connection is not ready
This PR is to fix [Issue 184](https://github.com/animir/node-rate-limiter-flexible/issues/184), and prevent slow response without falling back to insuranceLimiter if redis connection is lost
> RateLimiterRedis: track redis connection state

- lib/index.d.ts
Extend `IRateLimiterStoreOptions` type with `IRateLimiterRedisOptions` with new redis storage option `rejectIfRedisNotReady` to use its constructor from TS
> Add new option rejectIfRedisNotReady for RateLimiterRedis to index.d.ts

- lib/RateLimiterPostgres.js
- lib/index.d.ts
Default to public.
Used to let users define table in schema different from public.
> fix(postgres): add optional schema name parameter for postgres

- lib/RateLimiterPostgres.js
This commit adds clearExpiredByTimeout feature to RateLimiterPostgres.js when table is already created.
If there is not a reason this is missing and MySQL has it, then Postgres should support this, too.
> Add clearExpiredByTimeout to RateLimiterPostgres.js

- docker-compose.yml
- test/RateLimiterDynamo.test.js
This removes the need for starting it separately, leaving the use with only one command to run before running tests
> chore: start DynamoDB local with docker-compose

- .gitignore
- package.json
By adding `nyc` dependency, we can get complete coverage reports, both as HTML and inline summary in CLI.
When using `istanbul` directly, we see a lot of errors in the console and the HTML report looks a bit weird.
```sh
300 passing (1m)
=============================================================================
Writing coverage object [/Users/morgan/code/mroderick/node-rate-limiter-flexible/coverage/coverage.raw.json]
Writing coverage reports at [/Users/morgan/code/mroderick/node-rate-limiter-flexible/coverage]
=============================================================================
Handlebars: Access has been denied to resolve the property "statements" because it is not an "own property" of its parent.
You can add a runtime option to disable the check or this warning:
See …
```
> chore: Fix coverage reports

- lib/RateLimiterMongo.js
The getDriverVersion logic is resulting in a 0.0.0 version on the latest mongoose + mongodb versions due to topology being undefined, added logic to process the version properly if the field is undefined.
Details of the error can be found here: https://github.com/animir/node-rate-limiter-flexible/issues/251
> Fix client version for RateLimiterMongo

- .github/workflows/test.yml
This PR instructs GitHub Actions to also use cache for npm packages for the ESLint job. This will likely give a minor speedup for this job, and may prime the cache for the following job :)
> chore: also use cached npm packages for ESlint job

- test/ExpressBruteFlexible.test.js
- test/RateLimiterDynamo.test.js
- test/RateLimiterRedis.ioredis.test.js
- test/RateLimiterRedis.redis.test.js
- test/RedisOptions.js
Using 'localhost' causes problems on some systems, as redis client will try to connect to Docker using ipv6 (::1) instead of using ipv4. By using an ipv4 address (127.0.0.1), we're forcing use of ipv4, which works on more systems
---
Background: I was unable to run the tests successfully on my work computer, whereas they run fine on my personal computer. This PR should make it easier for more people (like myself) to contribute.
> chore: prefer 127.0.0.1 over 'localhost' in tests

- lib/RateLimiterRedis.js
- lib/index.d.ts
- test/RateLimiterRedis.ioredis.test.js
- test/RateLimiterRedis.redis.test.js
Allow providing a custom incrTtlLuaScript
> feat(redis): add customIncrTtlLuaScript option

- lib/RateLimiterDynamo.js
TLDR: Adds an option allowing users to skip the check for TTL settings when using the `RateLimiterDynamo`.
When assessing this library for use in a serverless environment (in this case AWS Lambda), we noticed that there was a significant overhead every time we instantiated a new rate limiter (so every time a new lambda started). This was due to `RateLimiterDynamo`'s behaviour which is to query the table to make sure that the TTL has been set up correctly.
While this is useful behavior on a long-running server, it doesn't make much sense in a serverless environment - once we've validated that the TTL is indeed set up correctly it doesn't make sense to keep checking it again and again and again.
I propose a new option which disables this check, in much the same way that you can disable …
> RateLimiterDynamo: Add key to skip querying ttl

- lib/RateLimiterPrisma.js
I noticed my app had hanging child processes when shutting down after introducing `RateLimiterPrisma`. Tracked it down to this timeout handler which is not being cleaned up
> fix(prisma): cleanup expiry timeout when process exits to prevent memory leak

- lib/RateLimiterSQLite.js
- package.json
- test/RateLimiterSQLite.test.js
This fixes an issue where an unused Knex connection remained open, causing pool connection problems. Additionally, this adds functions to run tests against Knex.
> fix(SQLite): close unclosed Knex connection
